### ISSUE TITLE
C API: RoboDK_Collisions does not appear in robodk_api_c.h

### ISSUE THREAD

**Issue by sjohnson-FLL** [RoboDK/RoboDK-API#109]
Pretty much the title.

There is no function prototype for the RoboDK_Collisions() function that is defined in robodk_api_c.c, which causes compiler errors when attempting to build code that uses that function.

(Note that RoboDK_Collision() IS defined, but the plural is not.)

**Comment by sambertrdk** [comment]
Fixed with https://github.com/RoboDK/RoboDK-API/pull/122
