### ISSUE TITLE
C API: Extraneous console prints present in robodk_api_c.c

### ISSUE THREAD

**Issue by sjohnson-FLL** [RoboDK/RoboDK-API#110]
The functions below each print once to the console. This is likely leftover from when the functions were being debugged. Printing statuses like this is at least not consistent with the behavior of other functions in the C API. Ideally, the prints would be removed, but at least they should have an option to disable console prints when calling the function.
`struct Mat_t Item_PoseFrame()`
`struct Mat_t Item_PoseTool()`

**Comment by RoboDK** [comment]
Thank you for letting us know. We just removed these unnecessary prints that were once added for debugging purposes.
