### ISSUE TITLE
Possible to overwrite motion planning module as a plugin?

### ISSUE THREAD

**Issue by XDinEuro** [RoboDK/RoboDK-API#117]
Hi, I am Yikai.

May I ask if I can overwrite motion planning module(moveJ moveL...) with my own implementations?

Motivation is i want to precisely simulate the circle time using my motion planners.

I am looking forward to your reply. Thanks

**Comment by sambertrdk** [comment]
As this is not an issue with the RoboDK API, this post was moved to our forum.
https://robodk.com/forum/Thread-Overwrite-IK-computation-and-moveL-using-plugin-interface
