### ISSUE TITLE
Using RoboDK Docker image

### ISSUE THREAD

**Issue by rwuthric** [RoboDK/RoboDK-API#118]
The `How to use this image` documentation of the [RoboDK docker image](https://hub.docker.com/r/robodk/robodk) says that connection to RoboDK within the image should be done as
```
RDK = robolink.Robolink(port=20501)
```
That doesnt seem correct to me. I had to use
```
RDK = robolink.Robolink(robodk_ip='127.0.0.1',
                        port=20501,
                        robodk_path='/home/user/RoboDK/bin/RoboDK')
```
Is this a bug in the documentation or on my side?

**Comment by sambertrdk** [comment]
If you bind the host port with the Docker container, it should work as intended:
`docker run -dp 20501:20501 -e RDK_PORT=20501 -e RDK_LIC=XXXX-XXXX-... -t robodk`

**Comment by rwuthric** [comment]
Correct. The main difference compared to the documentation if the usage of `robodk_path='/home/user/RoboDK/bin/RoboDK'`. Otherwise indeed works as documented.

**Comment by sambertrdk** [comment]
I will update the Docker Hub read me to include the port bind. Thank you!
