### ISSUE TITLE
Difference between Disconnect() and Finish()

### ISSUE THREAD

**Issue by rwuthric** [RoboDK/RoboDK-API#119]
What is the difference between [Disconnect](https://robodk.com/doc/en/PythonAPI/robodk.html?highlight=robolink#robodk.robolink.Robolink.Disconnect) and [Finish](https://robodk.com/doc/en/PythonAPI/robodk.html?highlight=robolink#robodk.robolink.Robolink.Disconnect) ?

The documentation of both functions calls are identical. If no difference why two function names? For backward compatibility?

**Comment by sambertrdk** [comment]
There is no difference. In fact, Robolink.Finish() calls Robolink.Disconnect(). This was kept for backward compatibility.
Note that Item.Disconnect() does not have the same behaviour.
