### ISSUE TITLE
RoboDK Python interface does not support v3.11

### ISSUE THREAD

**Issue by sclaiborne** [RoboDK/RoboDK-API#126]
Some of RoboDKs features requires PySide2 which is not supported after Python version 3.10. 

With my limited knowledge of QT, It sounds like changing to PySide6 for Python versions >3 would be an easy fix. 

There is a current work around:

1. Install the latest version of Python that that package supports (sounds like that's Python 3.10).
2. Copy that module's code from the site-packages folder of the Python 3.10 installation to the site-packages folder of the Python 3.11 installation.

**Comment by sambertrdk** [comment]
That is a nice workaround, thanks for sharing!
We are using PySide2 to match the Qt version of RoboDK itself.
You should not have any problem running the core of the API (robolink/robomath) with Python 3.11, as it does not depend on PySide2.
