### ISSUE TITLE
[Python] Optional argument "size" in robodk.eye not used 

### ISSUE THREAD

**Issue by c3dff** [RoboDK/RoboDK-API#19]
Function definition: def eye(size=4) would allow for multiple sizes of Identity Matrix to be created, however the argument is not used. Specifying size=3 instantiates a matrix of size 4 which is confusing for the user.
Behavior should be:
if size == 4:
    return Mat(4x4)
else:
    should either return a matrix of the proper size or raise NotImplementedError("Size other than 4 not supported")

**Comment by RoboDK** [comment]
Thank you for noticing. We just fixed this issue.
