### ISSUE TITLE
[Python] Robolink.CloseStation() is not static but is missing a "self" argument

### ISSUE THREAD

**Issue by TelluriumCrystal** [RoboDK/RoboDK-API#29]
I am working on some application code for a project and I ran into an issue trying to call `Robolink.CloseStation`. It appears that this function is missing the "self" argument required by 
instance functions.

Changing the [line](https://github.com/RoboDK/RoboDK-API/blob/1d8e60ce0c61300623bc08662a2106b7b44e7c15/Python/robolink.py#L1466) to `def CloseStation(self):` fixed it in my local build.

**Comment by RoboDK** [comment]
Thank you for noticing! We just fixed it in the main branch
