### ISSUE TITLE
Update to .Net Core 3.0

### ISSUE THREAD

**Issue by kellyprankin** [RoboDK/RoboDK-API#35]
I've updated the project for C# to .Net Core 3.0.

Are you interested in me opening a pull request? The changes are honestly very minimal to the code.

I'd need to update the Sample Project as well, but I first wanted to see if you would accept the PR or not.

**Comment by nubi86** [comment]
Yes, please go ahead! Thank you.

**Comment by kellyprankin** [comment]
@nubi86 Hello, I think I've completed it. I am going to open a PR now.
