### ISSUE TITLE
NameError: name 'Robolink' is not defined

### ISSUE THREAD

**Issue by tomekstankowski** [RoboDK/RoboDK-API#47]
When trying to execute the following script:
```
from robolink import *    # RoboDK's API
from robodk import *      # Math toolbox for robots

RDK = Robolink()

```
I'm getting `NameError: name 'Robolink' is not defined`. This happens on Ubuntu 20.04 when trying to execute script in terminal, however everything is fine when executing the script with RoboDK 5.0 gui. I installed robodk with `pip3 install robodk` but also tried setting PYTHONPATH: `export PYTHONPATH=/home/$USER/RoboDK/Python/` and then executing script with both `python` and `python3`.

**Comment by RoboDK** [comment]
Make sure to install RoboDK on the correct Python version. You can run the following code to know where you have Python installed:

```
import sys
print(sys.executable)
```
