### ISSUE TITLE
bool assigned to float 

### ISSUE THREAD

**Issue by sancelot** [RoboDK/RoboDK-API#55]
Hi,

_valid variable  is declared as double , but bool value is used. and seems unused....

https://github.com/RoboDK/RoboDK-API/blob/master/C%2B%2B/Example/robodk_api.h#L747

https://github.com/RoboDK/RoboDK-API/blob/master/C%2B%2B/Example/robodk_api.cpp#L190

**Comment by RoboDK** [comment]
Thank you for pointing this out. We just fixed this.
