### ISSUE TITLE
A few bugs in C API

### ISSUE THREAD

**Issue by Aeradan** [RoboDK/RoboDK-API#65]
Hi,
the new C API cannot compile with a clang compiler:
In robodk_api_c.h, line 292, 295, 296, 324, the char& variables in the function declarations should be char*
Same file, lines 324, the const Mat_t& tool_pose should be const struct Mat_t* tool_pose
Same file, line 349, the Joint_t& joints should be Joint_t* joint

These reflect in the function definitions in robodk_api_c.cpp
Moreover, in the .cpp file I find errors at
line 556, should be const struct Mat_t *tool_pose, const char *tool_name) {
line 560, should be *tool_pose
line 561, should be tool_name
line 674, correct typecasting should be (int)zonedata
line 689, no * operator, should be nofilename
line 721, should be *parameters
line 728, no * operator, should be parameters
line 1010, it is joints->_Values, joints->_nDOFs);

Keep up with the good job!

**Comment by vin-eet-singh** [comment]
@Aeradan Thank you pointing out the bugs. All these have been fixed. 
Let us know if you run into any other issues.
