### ISSUE TITLE
Error while loading shared libraries: libQt5WebSockets.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sunzengpeng** [RoboDK/RoboDK-API#69]
hello,i have an error when i run 

RDK = Robolink() 

in python3.6,ubuntu18.04,the error is 

error while loading shared libraries: libQt5WebSockets.so.5: cannot open shared object file: No such file or directory,

but i can find libQt5WebSockets.so.5 in my system and roboDK dirctory:

./usr/local/lib/python3.6/dist-packages/PyQt5/Qt5/lib/libQt5WebSockets.so.5
./home/sunzengpeng/RoboDK/bin/lib/libQt5WebSockets.so.5.12.0
./home/sunzengpeng/RoboDK/bin/lib/libQt5WebSockets.so
./home/sunzengpeng/RoboDK/bin/lib/libQt5WebSockets.so.5
./home/sunzengpeng/RoboDK/bin/lib/libQt5WebSockets.so.5.12

i would apprectiate so much if you can give me some suggestions.
thanks

**Comment by RoboDK** [comment]
This issue is probably related to starting RoboDK from Robolink. 

Can you start RoboDK manually using the shortcut on your Desktop?

Or using the command line:
`cd ~/RoboDK/`
`sudo RoboDK-Start.sh`
