### ISSUE TITLE
Mat.ToQuaternion() function have some problem.

### ISSUE THREAD

**Issue by cjyljhot** [RoboDK/RoboDK-API#72]
when input Mat is a particular value ,for example
Mat1:
{X= 0.000 mm , Y= 0.000 mm , Z= 0.000 mm , Rx=-180.000 deg , Ry=-45.000 deg , Rz= 0.000 deg}
Vector3d x2 = new Vector3d(0.7071, 0, -0.7071);
Vector3d y2 = new Vector3d(0, -1, 0);
Vector3d z2 = new Vector3d(-0.7071, 0, -0.7071);

Mat2:
{X= 0.000 mm , Y= 0.000 mm , Z= 0.000 mm , Rx=-180.000 deg , Ry=45.000 deg , Rz= 0.000 deg}
Vector3d x2 = new Vector3d(0.7071, 0, 0.7071);
Vector3d y2 = new Vector3d(0, -1, 0);
Vector3d z2 = new Vector3d(0.7071, 0, -0.7071);

the function gives the same result (0,0.92387952923661276,0,0.38268344027085205)
but Mat1 correct result should be (0,0.92387952923661276,0,-0.38268344027085205)
so I write a program to caculate it ，and I get the correct result. am I right?

        public static double[] ToQuaternion(Mat Ti)
        {
            var q1 = new double[4];
            var a1 = Ti[0, 0];
            var b1 = Ti[1, 1];
            var c1 = Ti[2, 2];
            q1[0] = 0.5 * Math.Sqrt(Math.Max(a1 + b1 + c1 + 1, 0));
            q1[1] = 0.5 * Math.Sqrt(Math.Max(a1 - b1 - c1 + 1, 0));
            q1[2] = 0.5 * Math.Sqrt(Math.Max(-a1 + b1 - c1 + 1, 0));
            q1[3] = 0.5 * Math.Sqrt(Math.Max(-a1 - b1 + c1 + 1, 0));
            double qMax = 0d;
            for (int i = 0; i < 4; i++)
            {
                if (q1[i] > qMax) qMax = q1[i];
            }
            if (q1[0] == qMax)//w
            {
                q1[1] = 0.25 * (Ti[2, 1] - Ti[1, 2]) / qMax;
                q1[2] = 0.25 * (Ti[0, 2] - Ti[2, 0]) / qMax;
                q1[3] = 0.25 * (Ti[1, 0] - Ti[0, 1]) / qMax;
            }
            if (q1[1] == qMax)//x
            {
                q1[0] = 0.25 * (Ti[2, 1] - Ti[1, 2]) / qMax;
                q1[2] = 0.25 * (Ti[0, 1] + Ti[1, 0]) / qMax;
                q1[3] = 0.25 * (Ti[2, 0] + Ti[0, 2]) / qMax;
            }
            if (q1[2] == qMax)//y
            {
                q1[0] = 0.25 * (Ti[0, 2] - Ti[2, 0]) / qMax;
                q1[1] = 0.25 * (Ti[0, 1] + Ti[1, 0]) / qMax;
                q1[3] = 0.25 * (Ti[2, 1] + Ti[1, 2]) / qMax;
            }
            if (q1[3] == qMax)//z
            {
                q1[0] = 0.25 * (Ti[1, 0] - Ti[0, 1]) / qMax;
                q1[1] = 0.25 * (Ti[0, 2] + Ti[2, 0]) / qMax;
                q1[2] = 0.25 * (Ti[2, 1] + Ti[1, 2]) / qMax;
            }
            return q1;
}

**Comment by sambertrdk** [comment]
@cjyljhot @RoboDK 

I tested the code below on Python, and it seems to handle this limit case. We'll ensure it doesn't make any regressions and push an update.

`        private static double[] ToQuaternion(Mat Ti)
        {
            double[] q = new double[4];

            double tr1 = 1.0 + Ti[0, 0] - Ti[1, 1] - Ti[2, 2];
            double tr2 = 1.0 - Ti[0, 0] + Ti[1, 1] - Ti[2, 2];
            double tr3 = 1.0 - Ti[0, 0] - Ti[1, 1] + Ti[2, 2];

            if ((tr1 > tr2) && (tr1 > tr3))
            {
                double S = Math.Sqrt(tr1) * 2.0;
                q[0] = (Ti[2, 1] - Ti[1, 2]) / S;
                q[1] = 0.25 * S;
                q[2] = (Ti[0, 1] + Ti[1, 0]) / S;
                q[3] = (Ti[0, 2] + Ti[2, 0]) / S;
            }
            else if ((tr2 > tr1) && (tr2 > tr3))
            {
                double S = Math.Sqrt(tr2) * 2;
                q[0] = (Ti[0, 2] - Ti[2, 0]) / S;
                q[1] = (Ti[0, 1] + Ti[1, 0]) / S;
                q[2] = 0.25 * S;
                q[3] = (Ti[1, 2] + Ti[2, 1]) / S;
            }
            else
            {
                double S = Math.Sqrt(tr3) * 2;
                q[0] = (Ti[1, 0] - Ti[0, 1]) / S;
                q[1] = (Ti[0, 2] + Ti[2, 0]) / S;
                q[2] = (Ti[1, 2] + Ti[2, 1]) / S;
                q[3] = 0.25 * S;
            }

            return q;
        }`

**Comment by cjyljhot** [comment]
great!

**Comment by RoboDK** [comment]
We are improving the conversion from poses to quaternion to have a more robust calculation that works effectively with noise. 
@sambertrdk's suggestion doesn't work well if you provide the identity matrix. We are planning to make it work for any pose input. 

The issue you are showing arises if you don't provide accurate values for your pose. We recommend you to provide double precision accuracy values to your pose values (X,Y,Z vectors) so you don't experience this behavior.

**Comment by cjyljhot** [comment]
@RoboDK @sambertrdk 
Thank you for your attention on my issue！

I test program again with double values, use original code，but I get same problem. 
I think mat1 and mat2 get correct value because Mat.FromTxyzRxyz()  give mat[0,0] and mat[0,2] different value (0.707106781186548,0.707106781186547)
but mat3[0,0] [0,2] and mat4[0,0] [0,2]  have same value. 

my test program:

private void caculateIt(){
            RoboDk.API.Mat mat1 = RoboDk.API.Mat.FromTxyzRxyz(0,0,0,-180.0,-45.0,0);  
            RoboDk.API.Mat mat2 = RoboDk.API.Mat.FromTxyzRxyz(0, 0, 0, -180.0, 45.0, 0); 
            double sqrt2 = Math.Sqrt(2.0)/2.0;
            RoboDk.API.Mat mat3 = new RoboDk.API.Mat(sqrt2, 0, -sqrt2, 0, 0, -1, 0, 0, -sqrt2, 0, -sqrt2, 0);
            RoboDk.API.Mat mat4 = new RoboDk.API.Mat(sqrt2, 0, sqrt2, 0, 0, -1, 0, 0, sqrt2, 0, -sqrt2, 0);
            double[] q1 = RoboDk.API.Mat.ToQuaternion(mat1);
            double[] q2 = RoboDk.API.Mat.ToQuaternion(mat2);
            double[] q3 = RoboDk.API.Mat.ToQuaternion(mat3);
            double[] q4 = RoboDk.API.Mat.ToQuaternion(mat4);
}

mat1 = 0.707106781186548 , 0 , -0.707106781186547 , 0 , 8.65927457071935E-17 , -1 , 8.65927457071936E-17 , 0 , -0.707106781186547 , -1.22460635382238E-16 , -0.707106781186548 , 0 , 0 , 0 , 0 , 1
mat2 = 0.707106781186548 , 0 , 0.707106781186547 , 0 , -8.65927457071935E-17 , -1 , 8.65927457071936E-17 , 0 , 0.707106781186547 , -1.22460635382238E-16 , -0.707106781186548 , 0 , 0 , 0 , 0 , 1
mat3 = 0.707106781186548 , 0 , -0.707106781186548 , 0 , 0 , -1 , 0 , 0 , -0.707106781186548 , 0 , -0.707106781186548 , 0 , 0 , 0 , 0 , 1
mat4 = 0.707106781186548 , 0 , 0.707106781186548 , 0 , 0 , -1 , 0 , 0 , 0.707106781186548 , 0 , -0.707106781186548 , 0 , 0 , 0 , 0 , 1

result(original code):
q1=0 , -0.923879532511287 , 5.26835606386175E-09 , 0.38268343236509
q2=0 , -0.923879532511287 , 5.26835606386175E-09 , -0.38268343236509
q3=0 , 0.923879532511287 , 5.26835606386175E-09 , 0.38268343236509
q4=0 , 0.923879532511287 , 5.26835606386175E-09 , 0.38268343236509

result(sambertrdk's code):
q1=-5.65694372839885E-17 , 0.923879532511287 , 2.34318281388422E-17 , -0.38268343236509
q2=-5.65694372839885E-17 , 0.923879532511287 , -2.34318281388422E-17 , 0.38268343236509
q3=0 , 0.923879532511287 , 0 , -0.38268343236509
q4=0 , 0.923879532511287 , 0 , 0.38268343236509

result(my code):
q1=-5.65694372839885E-17 , 0.923879532511287 , 2.34318281388422E-17 , -0.38268343236509
q2=-5.65694372839885E-17 , 0.923879532511287 , -2.34318281388422E-17 , 0.38268343236509
q3=0 , 0.923879532511287 , 0 , -0.38268343236509
q4=0 , 0.923879532511287 , 0 , 0.38268343236509

Thank you again for all your great work!!!

**Comment by sambertrdk** [comment]
#80
