### ISSUE TITLE
Edits proposal in connect functions

### ISSUE THREAD

**Issue by Aeradan** [RoboDK/RoboDK-API#94]
Please, consider these edits for file robodk_api_c.c (C API):

line 105: 	RoboDK_Connect(inst, "", ROBODK_DEFAULT_PORT, "", "");

delete lines 119 to 121

Regards

**Comment by RoboDK** [comment]
Why are you suggesting to delete these lines? This allows using the default port for the API or using a custom port.

**Comment by Aeradan** [comment]
Because inst->PORT is an uint16_t, so it cannot be < 0 by definition, so the whole clause makes no sense.

**Comment by RoboDK** [comment]
Thank you for your feedback, this makes sense. We just fixed this issue.
