### ISSUE TITLE
small mistake on German RoboDK website

### ISSUE THREAD

**Issue by TXAE** [RoboDK/RoboDK-API#97]
This is not about the API, but instead about your German website translation.

[https://robodk.com/de/](https://robodk.com/de/)

below "Roboter-Bearbeitung"

it has to be "die Roboterbahn" instead of the current "den Roboterbahn".

**Comment by TXAE** [comment]
Not a mistake, but sounds weird: [https://robodk.com/de/simulation](https://robodk.com/de/simulation)

Below "1. Wählen Sie Ihren Roboter aus"
"Zugang zur RoboDK umfangreichen Roboter-Bibliothek" should be "Zugang zur umfangreichen RoboDK Roboter-Bibliothek"

**Comment by TXAE** [comment]
[https://robodk.com/de/pricing](https://robodk.com/de/pricing)

Below "SCHULLIZENZ
2-JAHRES-ABONNEMENT"

"2-JAHRES-ABONNEMENT
NUR FÜR SCHULUNGSZWECKEN"

should be

"2-JAHRES-ABONNEMENT
NUR **ZU** SCHULUNGSZWECKEN"

OR

"2-JAHRES-ABONNEMENT
NUR FÜR SCHULUNGSZWECKE"

**Comment by RoboDK** [comment]
Thank you for your feedback! We just fixed it
